"""Added fields

Revision ID: 45c566fb92d9
Revises: b5a4b8c3ed2c
Create Date: 2025-03-10 22:32:15.140110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c566fb92d9'
down_revision: Union[str, None] = 'b5a4b8c3ed2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET created_at = NOW()") 
    op.alter_column('users', 'created_at', nullable=False)  


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('tags', 'created_at')
    # ### end Alembic commands ###

