"""Added category

Revision ID: 659d1c5068e5
Revises: 803f86c4ad1e
Create Date: 2025-04-14 12:54:46.689381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659d1c5068e5'
down_revision: Union[str, None] = '803f86c4ad1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'category')
    # ### end Alembic commands ###
