"""add description with default empty string

Revision ID: 79af261e2436
Revises: 3f3f509cd4d7
Create Date: 2025-04-03 19:42:09.254760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79af261e2436'
down_revision: Union[str, None] = '3f3f509cd4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))

    op.execute("UPDATE documents SET description = '' WHERE description IS NULL")

    op.alter_column('documents', 'description', nullable=False, existing_type=sa.Text(), server_default='')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
