"""Image url field addedt

Revision ID: 803f86c4ad1e
Revises: 82cc5f7b35f1
Create Date: 2025-04-14 12:28:23.106128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803f86c4ad1e'
down_revision: Union[str, None] = '82cc5f7b35f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'image_url')
    # ### end Alembic commands ###
