"""Add type field to Tag model with default

Revision ID: 82cc5f7b35f1
Revises: 79af261e2436
Create Date: 2025-04-14 12:25:11.788886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cc5f7b35f1'
down_revision: Union[str, None] = '79af261e2436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag_type', sa.String(), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'tag_type')
    # ### end Alembic commands ###
